# Generated by Django 5.1.7 on 2025-04-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizer',
            options={},
        ),
        migrations.AlterModelManagers(
            name='organizer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='username',
        ),
        migrations.AddField(
            model_name='organizer',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='organizer',
            name='phone',
            field=models.CharField(default='Default Name', max_length=15),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
