# Generated by Django 5.1.7 on 2025-05-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_organizer_options_alter_organizer_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organizer',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='organizer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
