# Generated by Django 5.1.3 on 2025-08-20 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_eventcategory_event_max_attendees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('trending', 'Trending'), ('expired', 'Expired')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventdashboard',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Upcoming', 'Upcoming'), ('Completed', 'Completed')], default='upcoming', max_length=20),
        ),
    ]
