# Generated by Django 5.1.3 on 2025-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_event_organizer_alter_event_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-08-21 07:29:00'),
            preserve_default=False,
        ),
    ]